### ISSUE TITLE
README has links to private repoistory

### ISSUE THREAD

**Issue by tpurcell90** [thejackal360/OpenPelt-Public#1]
The links in the README all point to the private repository and not the public one. While it should be easy to find the correct links from the descriptions, this should be corrected.

Also in the Report Bugs section you have a typo it should be: "[Github Issue Tracker](https://github.com/thejackal360/OpenPelt-Public/issues)"

**Comment by tpurcell90** [comment]
The git clone line should also come before `pip install -r requirements.txt` because one needs to have cloned the repo to get `requirements.txt`

**Comment by gdetor** [comment]
All the above issues have been addressed.
