### ISSUE TITLE
libngspice.so source code avaiability

### ISSUE THREAD

**Issue by tpurcell90** [thejackal360/OpenPelt-Public#2]
It would be better to provide the source code to libngspice via a submodule or at least instructions on how to build it, especially if we need to use a modified version of it (as the documentation implies). Providing the library itself restricts the use based on the available compilers/libraries on the system, and provide potential linking issues. I would add ngspice as a dependency and not provide the library file in the repository.

**Comment by thejackal360** [comment]
We have added an ngspice source submodule to the repo. We have also added a build_ngspice.sh script to the repo that automatically builds libngspice.so.

**Comment by danaraujocr** [comment]
the build_ngspice.sh file requires a YACC command that wasn't available on a new linux build.
