### ISSUE TITLE
`run_tecsim.sh` Fails if seperate `libngspice.so` file is installed

### ISSUE THREAD

**Issue by tpurcell90** [thejackal360/OpenPelt-Public#3]
The problem is: `LD_LIBRARY_PATH=$(pwd)/ngspice $run_command`

This line overwrites the `LD_LIBRARY_PATH` set as the environment variables and if `libngspice.so` is not inside the default directory or if `run_tecsim.sh` is run from a directory that is not the base directory then this will lead to a failure of all tests.

**Comment by thejackal360** [comment]
We have added README instructions for permanently overwriting the LD_LIBRARY_PATH variable:

echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/thejackal360-ngspice/lib" >> ~/.bashrc

The default path specified is the one in which the build_ngspice.sh script builds libngspice.so. However, users can easily change the path to their own libngspice.so location.

We also mention in the README that run_tecsim.sh is to be used in the repo's base directory. It is only meant to run the OpenPelt tests and not for the general use case.
