### ISSUE TITLE
Improved API or Examples

### ISSUE THREAD

**Issue by tpurcell90** [thejackal360/OpenPelt-Public#4]
It would be better if there was either a complete API or at least examples/tutorials including information about the systems that are being simulated. The API right now (code docstrings) describe what is going on for most of the functions, but  they don't describe what the input parameters do. Right now the only examples are the tests which have basic comments and do not actually describe what is going on. It would be difficult for a new comer to the code to understand what they should do to run a simulation, unless it is a simple modification of one of the tests.

**Comment by thejackal360** [comment]
\We have added new documentation for most of the API. It describes input parameters and return values for most functions. We have also added a short "Controller Development" section to the README. This describes how one would go about developing a custom controller algorithm. The tests serve as examples for how to integrate one's controller algorithm with the TEC circuit model.
